// src/containers/plants/Plantstype.ts
import type { PlantBaseCreateReq } from '@/services/plants/type';

export const initialForm = {
  pwplIdPrefix: '',
  pwplId: '',
  pwplNm: '',
  pwplTypeCd: '',
  pwplSttsCd: '',
  pwplSclCd: '',
  designCpct: 0,
  instlCpct: 0,
  lctnZip: '',
  roadNmAddr: '',
  lctnLotnoAddr: '',
  lctnDtlAddr: '',
  pwplLat: 0,
  pwplLot: 0,
  pwplXcrd: 0,
  pwplYcrd: 0,
  pmMsrstn: '',
  pltar: 0,
  premsShpNm: '',   // ✅ 추가 (필수)
  eqpmntQty: 0,
  systmVltg: 0,
  grdnt: 0,
  az: 0,
  pr: 0,
  weight: 1.5,
  bldgStrctNm: '',
  instlPlcNm: '',
  infraNm: '',
  asstFlctNm: '',
  ownrNm: '',
  operCoNm: '',
  cnstCoNm: '',
  instlYmd: '',
  cmrcoprYmd: '',
  pwplExpln: '',
  delYn: 'N',
  rgtrId: '',
  regDt: '',
  mdfrId: '',
  mdfcnDt: '',
  bcode: '',
  address: '',
  jibunAddress: '',
  roadAddress: '',
  sido: '',
  zonecode: '',
  loginId: '',
} satisfies PlantBaseCreateReq;