import { SearchFormFieldConfig } from '@/components/search-fields/search-form-fields.component';
import { AdminSignupForm, UserSignupForm } from '@/schemas/auth/auth';

// 일반 사용자 계정 생성 config
export const getUserSignupConfig = (
  isBusiness: boolean,
  handlers: {
    onDuplicateCheck: () => void;
    onValidityCheck: () => void;
    onAddressSearch: (type: 'address' | 'businessAddress') => void;
  },
): (SearchFormFieldConfig<UserSignupForm> | SearchFormFieldConfig<UserSignupForm>[])[] => [
  {
    key: 'seCd',
    label: '가입 구분',
    type: 'select',
    required: true,
    placeholder: '가입 구분 선택',
    options: [
      { label: '일반', value: 'N' },
      { label: '사업자', value: 'B' },
    ],
    gridSize: 6,
  },
  {
    key: 'acntId',
    label: 'ID',
    type: 'search-text',
    required: true,
    placeholder: '메일 주소를 입력해 주세요',
    searchText: '중복 확인',
    onSearchClick: handlers.onDuplicateCheck,
    gridSize: 6,
  },
  {
    key: 'pswd',
    label: '비밀번호',
    type: 'password',
    required: true,
    placeholder: '비밀번호를 입력해 주세요',
    gridSize: 6,
  },
  {
    key: 'pswdConfirm',
    label: '비밀번호 확인',
    type: 'password',
    required: true,
    placeholder: '확인을 위해 비밀번호 재입력해 주세요',
    gridSize: 6,
  },
  {
    key: 'name',
    label: '이름',
    type: 'text',
    required: true,
    placeholder: '이름을 입력해 주세요',
    gridSize: 6,
  },
  {
    key: 'phone',
    label: '연락처',
    type: 'mobile',
    required: true,
    placeholder: '-없이 숫자만 입력해 주세요',
    gridSize: 6,
  },
  {
    key: 'birth',
    label: '생년월일',
    type: 'text',
    placeholder: 'YYMMDD',
    gridSize: 6,
  },
  {
    key: 'eml',
    label: '보조 이메일',
    type: 'text',
    placeholder: '계정 찾기 시 사용할 이메일 주소 입력',
    gridSize: 6,
  },
  [
    {
      key: 'zip',
      label: '주소',
      type: 'search-text',
      searchText: '우편번호 검색',
      placeholder: '우편번호',
      readOnly: true,
      width: 240,
      gridSize: 6,
      onSearchClick: () => handlers.onAddressSearch('address'),
    },
    {
      key: 'roadNmAddr',
      type: 'text',
      placeholder: '도로명 주소',
      readOnly: true,
      gridSize: 6,
    },
    {
      key: 'lctnDtlAddr',
      type: 'text',
      placeholder: '상세주소를 입력해 주세요',
      gridSize: 6,
    },
  ],
  [
    {
      key: 'bzmnZip',
      label: '사업자 주소',
      type: 'search-text',
      placeholder: '우편번호',
      searchText: '우편번호 검색',
      readOnly: true,
      width: 240,
      gridSize: 6,
      required: isBusiness,
      disabled: !isBusiness,
      btnDisabled: !isBusiness,
      onSearchClick: () => handlers.onAddressSearch('businessAddress'),
    },
    {
      key: 'bzmnRoadAddr',
      type: 'text',
      placeholder: '도로명 주소',
      readOnly: true,
      gridSize: 6,
      required: isBusiness,
      disabled: !isBusiness,
    },
    {
      key: 'bzmnLotnoAddr',
      type: 'text',
      placeholder: '지번 주소',
      readOnly: true,
      gridSize: 6,
      required: isBusiness,
      disabled: !isBusiness,
    },
    {
      key: 'bzmnDtlAddr',
      type: 'text',
      placeholder: '상세주소를 입력해 주세요',
      gridSize: 6,
      required: isBusiness,
      disabled: !isBusiness,
    },
  ],
  {
    key: 'bzmnNm',
    label: '사업자명',
    type: 'text',
    placeholder: '사업자명을 입력해 주세요',
    gridSize: 6,
    required: isBusiness,
    disabled: !isBusiness,
  },
  {
    key: 'bzmnNo',
    label: '사업자 번호',
    type: 'search-text',
    placeholder: '-없이 숫자만 입력해 주세요',
    searchText: '유효성 체크',
    onSearchClick: handlers.onValidityCheck,
    gridSize: 6,
    required: isBusiness,
    disabled: !isBusiness,
  },
];

// 관리자 계정 생성 config
export const getAdminSignupConfig = (handlers: {
  onDuplicateCheck: () => void;
  onOrgNameSearch: () => void;
}): (SearchFormFieldConfig<AdminSignupForm> | SearchFormFieldConfig<AdminSignupForm>[])[] => [
  {
    key: 'acntId',
    label: '아이디',
    type: 'search-text',
    required: true,
    placeholder: '메일 주소를 입력해 주세요',
    searchText: '확인',
    onSearchClick: handlers.onDuplicateCheck,
    gridSize: 12,
  },

  {
    key: 'pswd',
    label: '비밀번호',
    type: 'password',
    required: true,
    placeholder: '비밀번호를 입력해 주세요',
    gridSize: 12,
  },
  {
    key: 'pswdConfirm',
    label: '비밀번호 확인',
    type: 'password',
    required: true,
    placeholder: '확인을 위해 비밀번호 재입력해 주세요',
    gridSize: 12,
  },
  {
    key: 'name',
    label: '이름',
    type: 'text',
    required: true,
    placeholder: '이름을 입력해 주세요',
    gridSize: 12,
  },
  {
    key: 'phone',
    label: '연락처',
    type: 'mobile',
    required: true,
    placeholder: '-없이 숫자만 입력해 주세요',
    gridSize: 12,
  },
  {
    key: 'eml',
    label: '보조 메일 주소',
    type: 'text',
    placeholder: '메일 주소를 입력해 주세요',
    gridSize: 12,
  },
  {
    key: 'deptName',
    label: '조직',
    type: 'search-text',
    required: true,
    placeholder: '조직명',
    searchText: '검색',
    gridSize: 12,
    onSearchClick: handlers.onOrgNameSearch,
  },
  {
    key: 'jbgdName',
    label: '직급',
    type: 'text',
    placeholder: '직급을 입력해 주세요',
    gridSize: 12,
  },
  {
    key: 'taskCn',
    label: '업무 내용',
    type: 'textarea',
    placeholder: '업무 내용을 입력해 주세요',
    gridSize: 12,
  },
];
