import { ColDef } from 'ag-grid-community';

// [운영관리 > 유지보수] 상세 분석 테이블 컬럼 정의
export const OPERATION_ANALYTICS_COLUMN: ColDef[] = [
  { field: 'plantName', headerName: '발전소' },
  { field: 'deviceName', headerName: '장치' },
  { field: 'generation', headerName: '발전량(kWh)' },
  { field: 'operationTime', headerName: '가동시간(h)' },
  { field: 'loss', headerName: '손실(kWh)' },
  { field: 'lossRate', headerName: 'Loss Rate(손실)' },
  { field: 'alarmCount', headerName: '알림' },
  { field: 'dispatchCount', headerName: '출동' },
];

// [운영관리 > 유지보수] 상세 분석 임시 데이터
export const OPERATION_ANALYTICS_ROW_DATA = [
  {
    plantName: '서울 발전소',
    deviceName: '터빈 A',
    generation: 12500,
    operationTime: 20,
    loss: 120,
    lossRate: 0.96,
    alarmCount: 3,
    dispatchCount: 1,
  },
  {
    plantName: '부산 발전소',
    deviceName: '배관 B',
    generation: 9800,
    operationTime: 18,
    loss: 250,
    lossRate: 0.93,
    alarmCount: 5,
    dispatchCount: 2,
  },
  {
    plantName: '인천 발전소',
    deviceName: '발전기 C',
    generation: 15000,
    operationTime: 22,
    loss: 60,
    lossRate: 0.99,
    alarmCount: 1,
    dispatchCount: 0,
  },
  {
    plantName: '서울 발전소',
    deviceName: '터빈 A',
    generation: 12500,
    operationTime: 20,
    loss: 120,
    lossRate: 0.96,
    alarmCount: 3,
    dispatchCount: 1,
  },
  {
    plantName: '부산 발전소',
    deviceName: '배관 B',
    generation: 9800,
    operationTime: 18,
    loss: 250,
    lossRate: 0.93,
    alarmCount: 5,
    dispatchCount: 2,
  },
  {
    plantName: '인천 발전소',
    deviceName: '발전기 C',
    generation: 15000,
    operationTime: 22,
    loss: 60,
    lossRate: 0.99,
    alarmCount: 1,
    dispatchCount: 0,
  },
  {
    plantName: '서울 발전소',
    deviceName: '터빈 A',
    generation: 12500,
    operationTime: 20,
    loss: 120,
    lossRate: 0.96,
    alarmCount: 3,
    dispatchCount: 1,
  },
  {
    plantName: '부산 발전소',
    deviceName: '배관 B',
    generation: 9800,
    operationTime: 18,
    loss: 250,
    lossRate: 0.93,
    alarmCount: 5,
    dispatchCount: 2,
  },
  {
    plantName: '인천 발전소',
    deviceName: '발전기 C',
    generation: 15000,
    operationTime: 22,
    loss: 60,
    lossRate: 0.99,
    alarmCount: 1,
    dispatchCount: 0,
  },
  {
    plantName: '서울 발전소',
    deviceName: '터빈 A',
    generation: 12500,
    operationTime: 20,
    loss: 120,
    lossRate: 0.96,
    alarmCount: 3,
    dispatchCount: 1,
  },
  {
    plantName: '부산 발전소',
    deviceName: '배관 B',
    generation: 9800,
    operationTime: 18,
    loss: 250,
    lossRate: 0.93,
    alarmCount: 5,
    dispatchCount: 2,
  },
  {
    plantName: '인천 발전소',
    deviceName: '발전기 C',
    generation: 15000,
    operationTime: 22,
    loss: 60,
    lossRate: 0.99,
    alarmCount: 1,
    dispatchCount: 0,
  },
  {
    plantName: '서울 발전소',
    deviceName: '터빈 A',
    generation: 12500,
    operationTime: 20,
    loss: 120,
    lossRate: 0.96,
    alarmCount: 3,
    dispatchCount: 1,
  },
  {
    plantName: '부산 발전소',
    deviceName: '배관 B',
    generation: 9800,
    operationTime: 18,
    loss: 250,
    lossRate: 0.93,
    alarmCount: 5,
    dispatchCount: 2,
  },
  {
    plantName: '인천 발전소',
    deviceName: '발전기 C',
    generation: 15000,
    operationTime: 22,
    loss: 60,
    lossRate: 0.99,
    alarmCount: 1,
    dispatchCount: 0,
  },
  {
    plantName: '서울 발전소',
    deviceName: '터빈 A',
    generation: 12500,
    operationTime: 20,
    loss: 120,
    lossRate: 0.96,
    alarmCount: 3,
    dispatchCount: 1,
  },
  {
    plantName: '부산 발전소',
    deviceName: '배관 B',
    generation: 9800,
    operationTime: 18,
    loss: 250,
    lossRate: 0.93,
    alarmCount: 5,
    dispatchCount: 2,
  },
  {
    plantName: '인천 발전소',
    deviceName: '발전기 C',
    generation: 15000,
    operationTime: 22,
    loss: 60,
    lossRate: 0.99,
    alarmCount: 1,
    dispatchCount: 0,
  },
  {
    plantName: '서울 발전소',
    deviceName: '터빈 A',
    generation: 12500,
    operationTime: 20,
    loss: 120,
    lossRate: 0.96,
    alarmCount: 3,
    dispatchCount: 1,
  },
  {
    plantName: '부산 발전소',
    deviceName: '배관 B',
    generation: 9800,
    operationTime: 18,
    loss: 250,
    lossRate: 0.93,
    alarmCount: 5,
    dispatchCount: 2,
  },
  {
    plantName: '인천 발전소',
    deviceName: '발전기 C',
    generation: 15000,
    operationTime: 22,
    loss: 60,
    lossRate: 0.99,
    alarmCount: 1,
    dispatchCount: 0,
  },
];
